DRAppPackage/force-app/main/default/objects/DR_App_FAQ__c/DR_App_FAQ__c.object-meta.xml
<CustomObject>
    <label>DR App FAQ</label>
    <nameField>
        <label>DR App FAQs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DR App FAQs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DRAppPackage/force-app/main/default/objects/DR_App_FAQ__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

DRAppPackage/force-app/main/default/classes/DRAppFaqsTest.cls
@isTest
public class DRAppFaqsTest {

    @isTest
    public static void testFaqs(){
        
        List<DR_App_FAQ__c>faqs = new List<DR_App_FAQ__c>();
        
        for(integer i=0;i<10;i++){
            DR_App_FAQ__c f = new DR_App_FAQ__c();
            f.Active__c = true;
            f.Body__c   = 'Testing 123';
            f.Name      = 'FAQ #'+i;
            
            faqs.add(f);
        }
        
        insert faqs;
        
        List<DR_App_FAQ__c>getFaqs = DRAppFaqs.getFaqs();
        
        system.assertEquals(10, getFaqs.size());
        
    }
}