DRAppPackage/force-app/main/default/objects/DR_Contact__c/DR_Contact__c.object-meta.xml
<CustomObject>
    <label>DR Contact(Offline)</label>
    <nameField>
        <label>DR Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DR Contacts(Offline)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DRAppPackage/force-app/main/default/objects/DR_Contact__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <formula>LEFT(Name, FIND(&quot; &quot;, Name)-1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>First Name</label>
    <type>Text</type>
</CustomField>

DRAppPackage/force-app/main/default/objects/DR_Contact__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Crisis Management Team</fullName>
            </value>
            <value>
                <fullName>DMG Media Senior Management</fullName>
            </value>
            <value>
                <fullName>DMGT Contacts</fullName>
            </value>
            <value>
                <fullName>Emergency Contacts</fullName>
            </value>
            <value>
                <fullName>Useful Contacts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DRAppPackage/force-app/main/default/classes/DRContactController.cls
public with sharing class DRContactController {
	
    @AuraEnabled
    public static List<DR_Contact__c> getContacts(String type){ 
        
        if(type == null){       
            return null;       
        }else if(type=='All'){
               return [SELECT id, Name, Email__c,Mobile__c,First_Name__c FROM DR_Contact__c];               
        }else{                    
               return [SELECT id, Name,Email__c,Mobile__c,First_Name__c FROM DR_Contact__c WHERE Type__c=:type];                   
             }        
    }
    
    @AuraEnabled
	public static List<ListView> getListViews() {
        
        List<ListView> listviews = [SELECT Id, Name FROM ListView WHERE SobjectType = 'DR_Contact__c'];
    
        return listviews;
	}
}