DRAppPackage/force-app/main/default/objects/DR_Centre__c/DR_Centre__c.object-meta.xml
<CustomObject>
    <label>DR Centre(Offline)</label>
    <nameField>
        <label>Meeting Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DR Centres(Offline)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DRAppPackage/force-app/main/default/objects/DR_Centre__c/fields/Street_Number__c.field-meta.xml
<CustomField>
    <fullName>Street_Number__c</fullName>
    <label>Street &amp; Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

DRAppPackage/force-app/main/default/classes/MeetingPointControllerTest.cls
@isTest
public class MeetingPointControllerTest {
    
	@isTest public static void createCentres(){  
        
        List<DR_Centre__c>insertCentres = new List<DR_Centre__c>();
            
            for(integer i=0;i<5;i++){
                
                DR_Centre__c c = new DR_Centre__c();
                c.Name = 'HQ'+i;
                c.Street_Number__c = '123 street';
                c.City__c = 'London';
                c.Post_Code__c ='NW95XD';
                
                insertCentres.add(c);
            }
        
        insert insertCentres;
        
        List<DR_Centre__c>meetingPoints = MeetingPointController.getMeetingPoints();
        
        system.assertEquals(5, meetingPoints.size());
  	}	
}